### ISSUE TITLE
Bug: Running on GitabCI requires super user permission

### ISSUE THREAD

**Issue by aviyam1811** [prescottprue/firebase-ci#43] opened 2019-04-15 19:14 UTC
I tried to use firebase-ci with gitlab-ci and when I tried to deploy I've got this exception:
```
ℹ Checking to see if firebase-tools is installed...
✖ Error: Error attempting to check for firebase-tools version.

 undefinedfs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/root/.npm/_npx/88/lib/node_modules/firebase/node_modules/grpc/package.json'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Run.parseOpts [as parseArgv] (/builds/aviyam1811/accountapp-web-application/node_modules/grpc/node_modules/node-pre-gyp/lib/node-pre-gyp.js:136:36)
    at Object.<anonymous> (/builds/aviyam1811/accountapp-web-application/node_modules/grpc/node_modules/node-pre-gyp/bin/node-pre-gyp:24:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
The user that run's the command can't reach the file for checking if firebase-tools existing because insufficient permissions.

**Comment by prescottprue** [comment] 2019-04-16 20:22
Interesting... I personally use Gitlab-ci with firebase-ci to do deployments of multiple projects [including fireadmin.io](https://github.com/prescottprue/fireadmin/blob/master/.gitlab-ci.yml). That said though, that project has `firebase-ci` in the dev dependencies, so it is already installed - but you are showing an error coming from just checking for the existence of it, so not sure that would fix it.

Can you provide your `gitlab-ci.yml` file or the whole project so I can attempt to replicate? Thanks for reporting!

**Comment by prescottprue** [comment] 2019-12-04 09:52
Closing since no reproduction steps were provided. @aviyam1811 if a `.gitlab-ci.yml` settings file is provided which can be used to replicate the mentioned issue, we can reopen.

**Closed by prescottprue** 2019-12-04 09:52 UTC
