### ISSUE TITLE
Error installing firebase-tools

### ISSUE THREAD

**Issue by ronihcohen** [prescottprue/firebase-ci#13] opened 2017-10-30 07:16 UTC
**Do you want to request a *feature* or report a *bug*?**  

Bug.

**What is the current behavior?**
I was trying to deploy [this](https://github.com/prescottprue/react-redux-firebase/tree/master/examples/complete/material) project, running `firebase-ci deploy -s` on travis produced the following error: `Error installing firebase-tools.` 

![](https://files.gitter.im/redux-firebase/Lobby/5lsT/image.png)

**What is the expected behavior?**

Should deploy the build on firebase

**Comment by prescottprue** [comment] 2017-10-30 07:49
May have found the cause of it. Working on a debug option to enable more logging as well as a fix.

**Comment by prescottprue** [comment] 2017-10-30 08:36
It turns out that the way that the promise wrapping of the npm install was handling errors did not correctly handle warnings from NPM.

The fix is included in [`v0.3.0`](https://github.com/prescottprue/firebase-ci/releases/tag/v0.3.0). Let me know if it doesn't work as expected. There is also now the `--info` (-i flag) option was added to the `deploy` command for getting more info back from the internal npm install.

**Closed by prescottprue** 2017-10-30 08:36 UTC
Labels: bug
